---

- name: remove ntp pool and replace with amazon time server
  replace:
    path: /etc/chrony.d/ntp-pool.sources
    regexp: '^pool [0-2]\.amazon\.pool\.ntp\.org iburst maxsources [1-2]'
    replace: ''
  
- name: 
  lineinfile:
    path: /etc/chrony.d/ntp-pool.sources
    line: 'server 169.254.169.123 prefer iburst minpoll 4 maxpoll 4'
    insertafter: EOF