# Standards: 0.11
---

- name: Restart sshd
  service:
    name: sshd
    state: restarted

- name: Restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: Restart auditd
  service:
    name: auditd
    state: restarted
  ignore_errors: true

- name: Update GRUB configuration
  shell: grub2-mkconfig -o /boot/grub2/grub.cfg
  args:
    executable: /bin/bash
  become: yes
  changed_when: false
