---

# 4.1.12 Ensure use of privileged commands is collected (Scored)

- name: 4.1.12 Populate a list of privileged binaries
  command: find / -xdev \( -perm -4000 -o -perm -2000 \) -type f
  register: privileged_binaries
  tags:
    - level-1
    - section-4
    - "4.1.12"
    - scored  

- name: 4.1.12 Ensure use of privileged commands is collected (Scored)
  lineinfile:
    dest: "{{ cis_audit_rules_filename }}"
    insertafter: EOF
    line: "-a always,exit -F path={{ item }} -F perm=x -F auid>=1000 -F auid!=4294967295 -k privileged"
  with_items: 
    -  '# 4.1.12 Ensure use of privileged commands is collected'
    -  "{{ privileged_binaries.stdout_lines }}"
  notify: Restart auditd
  tags:
    - level-1
    - section-4
    - "4.1.12"
    - scored
