# Standards: 0.11
---

# 1.6.1.3 Ensure SELinux policy is configured (Scored)

- name: 1.6.1.3 Ensure SELinux is not disabled
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUXTYPE=.*'
    replace: 'SELINUXTYPE=targeted'
  tags:
    - level-1
    - section-1
    - "1.1.11"
    - scored
