# Standards: 0.11
---

# 1.6.1.2. Ensure the SELinux state is enforcing (Scored)

- name: 1.6.1.2 Ensure SELinux is not disabled
  replace:
    path: /etc/selinux/config
    regexp: '^SELINUX=.*'
    replace: 'SELINUX=enforcing'
  tags:
    - level-1
    - section-1
    - "1.1.11"
    - scored
