# Standards: 0.11
---

# 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)

- name: Install the SE Linux requirements - libselinux-python
  command: yum install libselinux-python -y

- name: Install the SE Linux requirements - policycoreutils-python
  command: yum install policycoreutils-python -y

- name: pip3 install selinux
  command: pip3 install selinux

- name: 1.6.1.1 Ensure SELinux is not disabled in bootloader configuration (Scored)
  ansible.posix.selinux:
    policy: targeted
    state: enforcing
  tags:
      - level-1
      - section-1
      - "1.1.11"
      - scored
