# Standards: 0.11
---

# 2.2.1.1 Ensure time synchronisation is in use

- name: 2.2.1.1 - Ensure ntp is installed
  command: yum install ntp -y && yum remove chrony -y && systemctl enable ntpd.service
  when: cis_enable_ntp and not cis_enable_chrony
  tags:
    - level-1
    - section-4
    - "2.2.1.1"
    - not-scored

- name: 2.2.1.1 - Ensure chrony is installed
  command: yum install chrony -y && yum remove ntp -y && systemctl enable chronyd.service
  when: cis_enable_chrony and not cis_enable_ntp
  tags:
    - level-1
    - section-4
    - "2.2.1.1"
    - not-scored
