# Standards: 0.11
---

# 2.3.3 Ensure talk client is not installed

- name: 2.3.3 - Ensure talk client is not installed
  command: yum remove "talk" -y
  tags:
    - level-1
    - "2.3.3"
    - scored
