# Standards: 0.11
---

# 2.3.4 Ensure telnet client is not installed

- name: 2.3.4 - Ensure telnet client is not installed
  command: yum remove "telnet" -y
  tags:
    - level-1
    - section-2
    - "2.3.4"
    - scored
